### ISSUE TITLE
RFC: Revamping the Dnn Forge

### ISSUE THREAD

**Issue by valadas** [DNNCommunity/DnnForge#1]
The Dnn Forge used to be a dnn module to aggregate all community projects in one place, it is no longer on the Dnn website and has not been maintained in many years. We have the codebase and data available but:
1. The code is very old, in Visual Basic, no assembly (uses app_code), no build scripts, etc.
2. The data is available in csv files and from a quick look, a lot of it is also outdated and has many modules that have not been maintained in multiple years.

There have been multiple separate efforts to build replacements for this:
1. nvQuickPulse at https://github.com/nvisionative/nvQuickPulse (phone app)
2. Dnn Connect Community Extensions at https://www.dnn-connect.org/community/community-extensions (correct me if I am wrong, but I think this is an open content template)
3. Dnn Community Dashboard (Cannot find a link to it right now, but will update this when I do)
4. There has been interest in revamping the old Dnn Forge module.

After taking a look at all this, I would like us to build a new Forge module instead of revamping the old one. Something more modern that will fulfill our current needs and could become the single source of truth for the data used by other tools (the ones above and maybe one day reintegrate this into the Dnn Extensions UI). This new module would be placed on the upcoming new dnn community website.

I was thinking we could then manually load the relevant (still available) modules by hand from the data we have from the old Forge module.

I would like that module to be able to pull metadata from repositories (I think mostly github, but depending on what we find, we could add others), thinks like latest version, last update date, number of download, number of issues, number of bugs, etc. This will allow filtering and sorting and help us have a better view of the status of all those extensions, and help us better manage the core modules too. I would also like to have some categories (core modules, free open source modules, free but not open source modules, etc.) In addition to the automatic metadata pulled from that (or those) apis, we can also add our own fields that do not exists on those apis, such as latest dnn version tested on, categories, etc. 

This RFC is for collection general opinions on this project, I will add other rfcs after some discussions to define the data schema, then UI mockups, etc.

Any thoughts on this?

**Comment by david-poindexter** [comment]
@valadas - this sounds like a fantastic direction to pursue.  I’ll be happy to contribute to the effort.

**Comment by VashJuan** [comment]
So the forge was mainly a list of modules as I recall, but maybe included themes and other providers/extensions. For one take on how to implement this, you might consider: https://www.drupal.org/project/project_module/. I certainly agree we do need a centralized, authoritative list of GitHub projects, but might we want - someday - to expand this to services/themes/modules/consultant/etc.?

**Comment by valadas** [comment]
Yes, I would see it as any extension type.

**Comment by EPTamminga** [comment]
**Great idea!**

@valadas:  To answer your question: Dnn Connect Community Extensions at https://www.dnn-connect.org/community/community-extensions is an **Open Content template**.

My hope is that we do not get a completely new way of install manifests or another tool (e.g. NuGet), but a straightforward extension of the way current manifests work.

Please do not aim too high, let's work towards an MVP (Minimal Viable Product) bare metal working solution that can be extended over time.

**Comment by WillStrohl** [comment]
I agree that you're on the right track, Daniel.  Let's knock this out!  :) 

Since you're currently leading this effort, what do your next steps look like, and what do you need help with?

**Comment by valadas** [comment]
@EPTamminga yeah, this would just be collecting the extensions, linking to the extension packages, and providing APIs to other systems if needed (basically having a central source to feed other things in a possible future like the extensions page, other websites, maybe the store, etc.) This would not change anything to Dnn itself, (not touching the install process at all yet).

@hismightiness The next step I think would either be mocking up the UI or the data structure. I wanted to create this RFC first in case there are ideas that would affect both those things.

For the data structure, I think we need (this is very quick but needs to be better defined in a separate RFC): Extention Type (module, skin, provider, etc.), Kind (core module, open source extension, free extension), Categories (store, blog, language pack, forum, structured content, etc.). Then each extension would need at least: (name, short description, long description, repository, maintainer, download url,  probably many more, need to think about it more).

For the UI, I would like to have one public view for everyone navigating, then a maintainers worksheet view (maybe not public) that would replace the excel worksheet we have for the core modules, and an admin view to allow adding categories, deleting old unmaintained modules in the futures, making edits to correct typos, etc. I would also like a submission form for people to be able to submit new extensions that we can approved and add to the database, etc..

**Comment by valadas** [comment]
Also, we are not there yet until we have decided the data structure and UI mockups but what technologies are most of the people who will be contributing familiar with?

MVC vs SPA ?

if SPA
React, Angular, Vue, other ?

I am familiar with SPA and React personally, but don't want to go that route if everybody then complains they cannot contribute because it uses React and they are not familiar with it. By the way, if we go the React way, I will be starting it with the latest React features, so it will be strongly typed (typescript), use React new context Apis and hooks, probably will not need Redux on this with the latest React technologies.

**Comment by EPTamminga** [comment]
For me, it would be essential that in the "Extensions" host menu overview of extensions, it is signalled that:
- There is a new version
- If that version is compatible with the DNN version the site is running
- If there is a fee involved to obtain the new version
- A one-click install/update

If the Extension list can be filtered to **only show extensions that have updates**, it would help a lot to stay current.

**Comment by EPTamminga** [comment]
@valadas :
To answer your question re. technolgy: since the PB is based on SPA/React, it seem to me that that is the way to go for DNN.Forge

**Comment by WillStrohl** [comment]
I agree with a SPA approach, but not necessarily on React being the tech of choice.  It would be nice to see a Vue module released.  :)

**Comment by valadas** [comment]
Ok, so I will now close this RFC and open more granular issues, one for the Data Structure and one for the UI, feel free to discuss ideas on those, I will start now working on the data structure. Also after a couple of discussions outside this RFC, for now the only goal is to ha a place to list all open source extensions (it can be modules, skins, any type) and a github integration. Anything for now related to the update service, extension feed and store is out of scope for this initial round, but we keep that in mind to be able to extend to those places in the future if needed.
